---
- name : enforce  s3 bucket versioning on  aws account
  hosts: localhost
  gather_facts: false
  tasks:
    - name: list s3 buckets
      amazon.aws.s3_bucket_info:
      register: result
    - debug :
        var : result
    - name : enable   versioning on s3 bucket
      amazon.aws.s3_bucket:
        name: "{{item.name}}"
        versioning: yes
      loop: "{{result.buckets}}"